apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghw-deployment-sc-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghw-app-sc-vol
  template:
    metadata:
      labels:
        app: ghw-app-sc-vol
    spec:
      containers:
      - name: ghw-container-vol
        image: fajarsujailoyato/go-hello-world:1.0.0-rc1
        # envFrom:
        # - secretRef:
        #     name: sc-ghw
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/sh", "-c", "rm -f /app/.env && exit 0"]
        volumeMounts:
            - name: secret-volume
              mountPath: /app/.env
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: sc-ghw