apiVersion: v1
kind: Service
metadata:
  name: ghw-service-sc-vol
spec:
  type: NodePort
  ports:
    - port: 8001  # Port yang akan di-expose di dalam cluster
      targetPort: 8001  # Port yang dijalankan oleh container
      nodePort: 30001  # Port yang akan di-expose di node (dalam range 30000-32767 biasanya)
  selector:
    app: ghw-app-sc-vol  # Sesuaikan dengan label pada deployment yang ingin Anda expose